apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-temp-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: temp-app
  template:
    metadata:
      labels:
        app: temp-app
    spec:
      containers:
        - name: temp-app
          image: henryhiraki22/temperatura-app1:v2
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-temp-app
spec:
  selector:
    app: temp-app
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30000
  type: NodePort
